<?xml version="1.0" encoding="utf-8"?><Database Name="Problem2DB" EntityNamespace="DC" ContextNamespace="DC" Class="Problem2DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Problem2DB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Problem2DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pessoa" Member="Pessoas">
    <Type Name="Pessoa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataDeNascimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TelefoneResidencial" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>